### ISSUE TITLE
Feature request: Use our own API client ID

### ISSUE THREAD

**Issue by Flynn95** [Superjo149/auryo#164]
# 💡 Feature request

## What do you propose

Since SoundCloud limit API calls to 15000 per day, how about letting the user set his own client ID to continue using the app after it hit the limit?

## Whats steps can we take to implement it

We can use an JSON external file in user's home folder, the app check for the file's existence and get the necessary data.
I haven't read the source code so I'll come back to this later.

## Examples

The Soundnode app (https://github.com/Soundnode/soundnode-app) has implemented this, though incomplete but it works.

**Comment by Superjo149** [comment]
Yeah, that's possible. Luckily we haven't hit the limit just yet.

 I was thinking perhaps we could write a chrome extension to intercept the client_id, pretty sure this is possible (https://medium.com/@gilfink/adding-web-interception-abilities-to-your-chrome-extension-fb42366df425).

if we can do this, we can handle this in a very clean way. 
- User installs extension => 
  - User presses login on Auryo =>
    - Browserwindow opens with SoundCloud =>
      - (User logs in) the extension fetches the clientId and sends it to the app via sockets just like the normal auth process

**Comment by N33G** [comment]
Quick question on the subject if this gets implemented what does it means to the limit on third party apps access will it let stream all tracks, or i am totally missing the point. Thanks in advance.

**Comment by Superjo149** [comment]
@N33G Limit will be gone and you'll see more tracks I think. But it's technically against SoundCloud TOS.

**Comment by N33G** [comment]
I will keep an eye on the subject. This in one of the reasons keeping me from using Auryo full time.

**Comment by Superjo149** [comment]
@N33G Which one? not having all tracks available? Or the limit?

**Comment by N33G** [comment]
The limit haven't been a problem really. Is just some tracks on playlists don't match with the web version or don't follow the sort order.

**Comment by chrismessina** [comment]
> Luckily we haven't hit the limit just yet.

If this continues to be true, then I suppose this issue should remain low priority. If it becomes more of an issue, I still don't see a problem with having users register their own SoundCloud API client and simply entering their client and secret into an Advanced panel in Preferences. Yes, it would be an advanced feature, but would address the limitation effectively. 

[Spotificious for Alfred](https://ben.stolovitz.com/Spotify-for-Alfred/) requires users to get a Spotify app client ID and secret in order to perform client-side searching of the user's Spotify account, and it isn't that difficult.

**Comment by Superjo149** [comment]
@chrismessina Yes indeed. My reason for the `hacky` workaround idea using the chrome extension is that there are only so many people who already have a SoundCloud client & secret. SoundCloud stopped issues new ones last year I believe.

**Comment by chrismessina** [comment]
Wow, didn't realize they stopped issuing new client IDs. Lame!

**Comment by LandKingdom** [comment]
> SoundCloud client & secret
So I'd also need a secret key? 
Does that mean SoundNode's ability to add your own clientId isn't sufficient anymore?

I'm asking because I tried SoundNode first since I had already heard of it. Then I tried yours and I personally enjoy it more (great work, seriously!). I went looking for a clientId thing but couldn't find it so I wanted to see if I could contribute and add this functionality, but if we also need a "secret" then I need to know what's that first!
