### ISSUE TITLE
Liked tracks not updating in the App

### ISSUE THREAD

**Issue by Baitinq** [Superjo149/auryo#167]
Hi, I am using Auryo-bin 2.3.1 on Arch.

Theres a minor problem with the liked tracks not being updated in the app. When I like a track on streamcloud or Auryo it doesnt show in the licked tracks on Auryo, but it does on Sounclouds website.

Thanks for reading this :)

**Comment by Superjo149** [comment]
Do they also not appear after restarting? Or are they not showing up whatsoever?

**Comment by Baitinq** [comment]
No they are simply not showing up

**Comment by Baitinq** [comment]
I think this might be a recent problem because in shows some tracks that i liked a couple of weeks ago, but not recently liked tracks (+- 1 week)

**Comment by Superjo149** [comment]
They might just not be available via a third party application like Auryo. This is one of the limitations. You could check this by pasting the SoundCloud url in the search bar in Auryo. If you get redirected back to the browser you aren't able to view/listen to this via Auryo. Otherwise you would just be redirected to the track page in Auryo itself.

**Comment by Baitinq** [comment]
Yes that is the problem, thank you for the quick responses.
