### ISSUE TITLE
Use real programming lang

### ISSUE THREAD

**Issue by Kreyren** [Superjo149/auryo#202]
Assuming this beeing just browser with soundcloud API that has defined functions in GUI -> Why not use C++/Rust based core for this instead of slow electron?

Something like https://github.com/servo/servo would be ideall.

Reason: Speed, reliability and optimization of auryo on high-end linux systems for system dependencies + more appealing to contrib.

**Comment by jbergstroem** [comment]
> Why not use C++/Rust based core for this instead of slow electron?
I'm sure the main developers would appreciate help via pull requests in this regard!

**Comment by Kreyren** [comment]
> > Why not use C++/Rust based core for this instead of slow electron?
> 
> I'm sure the main developers would appreciate help via pull requests in this regard!

Doubt assuming that people that are using electron are usually closed in their own bubble saying that it's easier to maintain.. :thinking:

**Comment by Superjo149** [comment]
@Kreyren Welcome to my bubble. I really like working with Electron. I has it disadvantages, yes. But it has improved a lot since the early days. Auryo is a passion project of mine, I do not earn anything with this. So rewriting everything to servo or something else is not something I will be spending my time one. Yes, technically, it's just a browser app. But the Electron API & Browserwindow are too tightly coupled to easily port it. But like @jbergstroem mentioned, feel free to do so and create a PR. 😄

**Comment by Kreyren** [comment]
>  But like @jbergstroem mentioned, feel free to do so and create a PR. 

Assuming that you will maintain it?

**Comment by Superjo149** [comment]
@Kreyren If you port the app, i doubt that you are lazy. I think that will depend on how hard it is to integrate native features into it. And it will take time. I barely have time to maintain this.

**Comment by Kreyren** [comment]
Well the most complicated part is servo, but that can be synced with upstream so just making patch for servo that adds GUI options and loads requested API should be very intuitive.

i'm currently busy and not the best in rust, but i can try something in two weeks. (maybe sooner)

**Comment by Kreyren** [comment]
EDIT: rust has soundcloud crate already https://crates.io/crates/soundcloud
